# Check or edit all secrets to match yours.
# Power metering isn't calibrated.

substitutions:
  devicename: rgb_smart_plug_10a
  friendly_name: RGB Smart Plug 10A
  device_description: 10A Smart Plug with button and RGB led.

esphome:
  name: $devicename
  comment: ${device_description}

esp8266:
  board: esp01_1m

wifi:
  reboot_timeout: 0s
  networks:
  - ssid: !secret wifi_primary_ssid
    password: !secret wifi_primary_password
  - ssid: !secret wifi_secondary_ssid
    password: !secret wifi_secondary_password
  ap:
    ssid: ${device_name}_AP

captive_portal:

api:
  encryption:
    key: XC6kLNt3hj2JENuPPsX+CSq2bDcUx/3VaDyrkmFXkNE=
  reboot_timeout: 0s

ota:
  - platform: esphome
    id: ha_ota
    password: !secret ota_api_password

# Enable logging
logger:
  baud_rate: 0 #disable UART logging since we aren't connected to GPIO1 TX

# Web server can be removed after enabling HA API
web_server:
  port: 80

# Enable time component for use by daily power sensor
time:
  - platform: homeassistant
    id: homeassistant_time

sensor:
  # Reports how long the device has been powered (in minutes)
  - platform: uptime
    name: ${friendly_name} Uptime
    filters:
      - lambda: return x / 60.0;
    unit_of_measurement: minutes

  # Reports the WiFi signal strength
  - platform: wifi_signal
    name: ${friendly_name} Wifi Signal
    update_interval: 60s

binary_sensor:
  # Reports if this device is Connected or not
  # - platform: status
  #   name: ${friendly_name} Status

  # Button on the side is pressed and then toggle relay
  - platform: gpio
    device_class: power
    pin:
      number: GPIO13
      inverted: True
    name: ${friendly_name} Button # Name to make button visible in HA
    on_press:
      - switch.toggle: relay

text_sensor:
  # Reports the ESPHome Version with compile date
  - platform: version
    name: ${friendly_name} ESPHome Version

  # Reports detailed wifi info, can be commented out
  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
    # ssid: # Some additional wifi info that is not normally needed
    #   name: ${friendly_name} Connected SSID
    # bssid:
    #   name: ${friendly_name} Connected BSSID

switch:
  # Relay itself
  - platform: gpio
    name: ${friendly_name}
    pin: GPIO15
    id: relay
    restore_mode: RESTORE_DEFAULT_OFF #Try to restore relay state after reboot/power-loss event.
    #RESTORE_DEFAULT_OFF (Default) - Attempt to restore state and default to OFF if not possible to restore. Uses flash write cycles.
    #RESTORE_DEFAULT_ON - Attempt to restore state and default to ON. Uses flash write cycles.
    #ALWAYS_OFF - Always initialize the pin as OFF on bootup. Does not use flash write cycles.
    #ALWAYS_ON - Always initialize the pin as ON on bootup. Does not use flash write cycles.
    #on_turn_on: # Action when relay is turned on
    #  - script.execute: led_power_on
    #on_turn_off: # Action when relay is turned off
    #  - script.execute: led_relay_off

output:
  # Output GPIOs for RGB led
  - platform: esp8266_pwm # Red
    id: red_output
    pin: GPIO0
  - platform: esp8266_pwm # Green
    id: green_output
    pin: GPIO2
  - platform: esp8266_pwm # Blue
    id: blue_output
    pin: GPIO5

light:
  # RGB light
  - platform: rgb
    name: ${friendly_name} Light
    id: rgb_light
    red: red_output
    green: green_output
    blue: blue_output
    default_transition_length: 0.5s
    restore_mode: ALWAYS_OFF
    effects: # List some effects
      - strobe
      - flicker
      - random

# Blink the red light if we aren't connected to WiFi. Could use https://esphome.io/components/status_led.html instead but then we couldn't use the red light for other things as well.
# Only if not connected after 30s
interval:
  - interval: 2000ms
    then:
      - if:
          condition:
            for:
              time: 30s
              condition:
                not:
                  wifi.connected:
          then:
            - light.turn_on:
                id: rgb_light
                brightness: 100%
                red: 100%
                green: 0%
                blue: 0%
                flash_length: 250ms

script:
  - id: led_relay_off # Normal operation when relay is off
    then:
      - light.turn_off:
          id: rgb_light
  - id: led_power_on # Normal operation when relay is on
    then:
      - light.turn_on:
          id: rgb_light
          brightness: 80%
          red: 0%
          green: 100%
          blue: 50%